// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks_interactor

import (
	entity "base/internal/usecases/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"

	request "base/internal/handler/api/request"
)

// UserInteractor is an autogenerated mock type for the UserInteractor type
type UserInteractor struct {
	mock.Mock
}

type UserInteractor_Expecter struct {
	mock *mock.Mock
}

func (_m *UserInteractor) EXPECT() *UserInteractor_Expecter {
	return &UserInteractor_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, req
func (_m *UserInteractor) GetByID(ctx context.Context, req *request.GetByIdReq) (*entity.GetUserResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.GetUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.GetByIdReq) (*entity.GetUserResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.GetByIdReq) *entity.GetUserResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.GetUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.GetByIdReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserInteractor_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type UserInteractor_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - req *request.GetByIdReq
func (_e *UserInteractor_Expecter) GetByID(ctx interface{}, req interface{}) *UserInteractor_GetByID_Call {
	return &UserInteractor_GetByID_Call{Call: _e.mock.On("GetByID", ctx, req)}
}

func (_c *UserInteractor_GetByID_Call) Run(run func(ctx context.Context, req *request.GetByIdReq)) *UserInteractor_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*request.GetByIdReq))
	})
	return _c
}

func (_c *UserInteractor_GetByID_Call) Return(_a0 *entity.GetUserResponse, _a1 error) *UserInteractor_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserInteractor_GetByID_Call) RunAndReturn(run func(context.Context, *request.GetByIdReq) (*entity.GetUserResponse, error)) *UserInteractor_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserInteractor creates a new instance of UserInteractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserInteractor(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserInteractor {
	mock := &UserInteractor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
